services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: echo-backend
    container_name: echo_backend
    restart: unless-stopped
    ports:
      - "8082:3000"
    env_file:
      - /home/dev/secrets/echo-back.env
    volumes:
      - ./apps/backend/prisma:/app/apps/backend/prisma
    networks:
      - echo_network
    healthcheck:
      test: [ "CMD-SHELL", "node -e \"require('http').get('http://localhost:3001/api/api/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})\"" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    image: echo-frontend
    container_name: echo_frontend
    restart: unless-stopped
    ports:
      - "8083:3000"
    env_file:
      - /home/dev/secrets/echo-front.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - echo_network

networks:
  echo_network:
    driver: bridge
